# Generated by Django 2.1.15 on 2025-09-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach'),
        ),
    ]
