# Generated by Django 5.2.1 on 2025-09-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='L', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default='17:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
