# Generated by Django 5.2.1 on 2025-09-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_day_activity_end_time_activity_image_and_more'),
        ('athletes', '0003_remove_athlete_enrolled_activities_alter_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='athletes',
            field=models.ManyToManyField(blank=True, related_name='enrolled_activities', to='athletes.athlete'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default='17:00'),
        ),
    ]
