# Generated by Django 5.2 on 2025-09-16 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activity_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='athletes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'athlete'}, related_name='enrolled_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
