# Generated by Django 5.2.1 on 2025-09-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='enrolled_activities',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
