# Generated by Django 2.1.15 on 2025-09-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_remove_athlete_enrolled_activities_alter_athlete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
