# Generated by Django 5.2.1 on 2025-09-11 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_image_athleteprofile_coachprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('athletes', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'athlete'}, related_name='enrolled_activities', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'user_type': 'coach'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='participants', to='users.activity'),
        ),
    ]
