# Generated by Django 2.1.15 on 2025-09-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250915_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activities',
        ),
    ]
