# Generated by Django 5.2 on 2025-09-16 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_activity_id_alter_athleteprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='athletes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'athlete'}, related_name='coach_enrolled_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
