# Generated by Django 2.1.15 on 2025-09-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_alter_coach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
